### ISSUE TITLE
fix documentation to use ssm-commander instead of aws-ssm-commander

### ISSUE THREAD

**Issue by MAliNaqvi** [djcrabhat/aws-ssm-commander#1]
README says to use aws-ssm-commander, instead it should be ssm-commander

```
$ pipsi install aws-ssm-commander

$ aws-ssm-commander
-bash: aws-ssm-commander: command not found

$ ssm-commander
Usage: ssm-commander [OPTIONS] COMMAND [ARGS]...

Options:
  --debug
  --help   Show this message and exit.
```

Alternatively modifying this line to aws-ssm-commander:
https://github.com/djcrabhat/aws-ssm-commander/blob/master/setup.py#L23

**Comment by djcrabhat** [comment]
@MAliNaqvi thanks so much for filing this! You'll have to `pip install --upgrade aws-ssm-commander` to get this fix, as I bumped to version `0.0.2`, but appreciate you pointing out this inconsistency a bunch!

**Comment by djcrabhat** [comment]
I've uploaded new version to https://pypi.org/project/aws-ssm-commander/ .  I'll close out this issue once you confirm this upgrade works for you.

**Comment by MAliNaqvi** [comment]
Upgrade works! Can be closed.
