### ISSUE TITLE
Is it possible to add support for localstack

### ISSUE THREAD

**Issue by gwsu2008** [djcrabhat/aws-ssm-commander#7]
Hi, This tool is very useful for updating parameter store. I would like to have it also support localstack. https://github.com/localstack/localstack

Thanks

--Guang

**Comment by djcrabhat** [comment]
:) so glad you enjoy it.  Think that's a great idea!  Will add a "endpoint_url" param and pass it on to the session

**Comment by gwsu2008** [comment]
:) Thank you!

**Comment by djcrabhat** [comment]
Released 0.0.4  https://pypi.org/project/aws-ssm-commander/ .  You should find the flag `--ssm-override-url` on all subcommands and `--kms-override-url` on the `write` subcommand, and point those to your localstack urls!  Tell me if you have any trouble with this, I'll close up the ticket once you give me the 👍 

```
aws-ssm-commander tree  --ssm-override-url=http://localhost:4583 abc/123
```

**Comment by gwsu2008** [comment]
Thank you for the quick turnaround. I tried it and it worked like a charm.
:-)

Thanks

--Guang

**Comment by djcrabhat** [comment]
Beautiful!  Glad I could help.  Closing now.
